[package]
name = "tokr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
notify = "8.2.0"
tokr-config = { version = "0.1.0", path = "../../crates/tokr-config" }
tokr-diagnostics = { version = "0.1.0", path = "../../crates/tokr-diagnostics" }
tokr-driver = { version = "0.1.0", path = "../../crates/tokr-driver" }
tokr-ir = { version = "0.1.0", path = "../../crates/tokr-ir" }
tokr-lexer = { version = "0.1.0", path = "../../crates/tokr-lexer" }
tokr-parser = { version = "0.1.0", path = "../../crates/tokr-parser" }
